#ifndef CONFIG_HPP
#define CONFIG_HPP

#include <SDL2/SDL.h>

#define MAZE_WIDTH 20
#define MAZE_HEIGHT 20

#define MOVE_SPEED 0.05
#define ROTATE_SPEED 0.05
#define FOV 0.66

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define FORWARD SDL_SCANCODE_W
#define BACKWARD SDL_SCANCODE_S
#define LEFT SDL_SCANCODE_A
#define RIGHT SDL_SCANCODE_D

#define ROTATE_LEFT SDL_SCANCODE_LEFT
#define ROTATE_RIGHT SDL_SCANCODE_RIGHT

#define EXIT SDL_SCANCODE_ESCAPE

#endif
